
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Compilador.Sintactic;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int DOSPUNTS = 15;
  public static final int fer = 33;
  public static final int tupla = 29;
  public static final int MULT = 9;
  public static final int main = 38;
  public static final int retorna = 35;
  public static final int IGIG = 22;
  public static final int LPAREN = 10;
  public static final int RPAREN = 11;
  public static final int NOT = 25;
  public static final int AND = 24;
  public static final int caracter = 28;
  public static final int sortidaS = 37;
  public static final int OR = 23;
  public static final int si = 30;
  public static final int SUMAHI = 12;
  public static final int ASSIGN = 14;
  public static final int ID = 2;
  public static final int LCLAUDAT = 17;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int mentres = 32;
  public static final int COMA = 20;
  public static final int DIF = 21;
  public static final int ADD = 7;
  public static final int entradaS = 6;
  public static final int constant = 36;
  public static final int vcaracter = 5;
  public static final int PUNT = 19;
  public static final int vlogic = 4;
  public static final int metode = 34;
  public static final int logic = 27;
  public static final int RESTAHI = 13;
  public static final int venter = 3;
  public static final int PUNTICOMA = 16;
  public static final int enter = 26;
  public static final int RCLAUDAT = 18;
  public static final int SUB = 8;
  public static final int sino = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "venter",
  "vlogic",
  "vcaracter",
  "entradaS",
  "ADD",
  "SUB",
  "MULT",
  "LPAREN",
  "RPAREN",
  "SUMAHI",
  "RESTAHI",
  "ASSIGN",
  "DOSPUNTS",
  "PUNTICOMA",
  "LCLAUDAT",
  "RCLAUDAT",
  "PUNT",
  "COMA",
  "DIF",
  "IGIG",
  "OR",
  "AND",
  "NOT",
  "enter",
  "logic",
  "caracter",
  "tupla",
  "si",
  "sino",
  "mentres",
  "fer",
  "metode",
  "retorna",
  "constant",
  "sortidaS",
  "main"
  };
}

