
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package Compilador.Sintactic;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int INTERROG = 22;
  public static final int DOSPUNTS = 20;
  public static final int fer = 47;
  public static final int tupla = 39;
  public static final int MULT = 10;
  public static final int main = 54;
  public static final int seleccio = 42;
  public static final int IGIG = 29;
  public static final int LPAREN = 13;
  public static final int LCORCH = 23;
  public static final int MENORI = 30;
  public static final int vdecimal = 3;
  public static final int RPAREN = 14;
  public static final int vcadena = 6;
  public static final int pdefecte = 44;
  public static final int RCORCH = 24;
  public static final int caracter = 38;
  public static final int AUTOSUM = 16;
  public static final int sortidaS = 53;
  public static final int si = 40;
  public static final int SUMAHI = 18;
  public static final int DIV = 11;
  public static final int MAJOR = 33;
  public static final int ASSIGN = 15;
  public static final int AUTOSUB = 17;
  public static final int retur = 50;
  public static final int ID = 2;
  public static final int LCLAUDAT = 25;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int mentres = 46;
  public static final int COMA = 27;
  public static final int DIF = 28;
  public static final int ADD = 8;
  public static final int entradaS = 52;
  public static final int MENOR = 32;
  public static final int constant = 51;
  public static final int MOD = 12;
  public static final int vcaracter = 7;
  public static final int MAJORI = 31;
  public static final int cas = 43;
  public static final int vlogic = 5;
  public static final int metode = 49;
  public static final int logic = 36;
  public static final int RESTAHI = 19;
  public static final int venter = 4;
  public static final int acaba = 45;
  public static final int PUNTICOMA = 21;
  public static final int per = 48;
  public static final int enter = 35;
  public static final int RCLAUDAT = 26;
  public static final int SUB = 9;
  public static final int decimal = 34;
  public static final int sino = 41;
  public static final int cadena = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "vdecimal",
  "venter",
  "vlogic",
  "vcadena",
  "vcaracter",
  "ADD",
  "SUB",
  "MULT",
  "DIV",
  "MOD",
  "LPAREN",
  "RPAREN",
  "ASSIGN",
  "AUTOSUM",
  "AUTOSUB",
  "SUMAHI",
  "RESTAHI",
  "DOSPUNTS",
  "PUNTICOMA",
  "INTERROG",
  "LCORCH",
  "RCORCH",
  "LCLAUDAT",
  "RCLAUDAT",
  "COMA",
  "DIF",
  "IGIG",
  "MENORI",
  "MAJORI",
  "MENOR",
  "MAJOR",
  "decimal",
  "enter",
  "logic",
  "cadena",
  "caracter",
  "tupla",
  "si",
  "sino",
  "seleccio",
  "cas",
  "pdefecte",
  "acaba",
  "mentres",
  "fer",
  "per",
  "metode",
  "retur",
  "constant",
  "entradaS",
  "sortidaS",
  "main"
  };
}

