
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Compilador.Sintactic;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int INTERROG = 21;
  public static final int DOSPUNTS = 19;
  public static final int fer = 49;
  public static final int tupla = 41;
  public static final int MULT = 9;
  public static final int main = 57;
  public static final int seleccio = 44;
  public static final int retorna = 52;
  public static final int IGIG = 29;
  public static final int LPAREN = 12;
  public static final int LCORCH = 22;
  public static final int MENORI = 30;
  public static final int vdecimal = 3;
  public static final int RPAREN = 13;
  public static final int afegeix = 59;
  public static final int pdefecte = 46;
  public static final int NOT = 36;
  public static final int AND = 35;
  public static final int RCORCH = 23;
  public static final int caracter = 40;
  public static final int borra = 58;
  public static final int AUTOSUM = 14;
  public static final int sortidaS = 56;
  public static final int OR = 34;
  public static final int si = 42;
  public static final int SUMAHI = 16;
  public static final int DIV = 10;
  public static final int MAJOR = 33;
  public static final int ASSIGN = 18;
  public static final int AUTOSUB = 15;
  public static final int ID = 2;
  public static final int LCLAUDAT = 24;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int mentres = 48;
  public static final int COMA = 27;
  public static final int DIF = 28;
  public static final int ADD = 7;
  public static final int entradaS = 55;
  public static final int MENOR = 32;
  public static final int constant = 54;
  public static final int MOD = 11;
  public static final int vcaracter = 6;
  public static final int PUNT = 26;
  public static final int MAJORI = 31;
  public static final int cas = 45;
  public static final int vlogic = 5;
  public static final int metode = 51;
  public static final int logic = 39;
  public static final int RESTAHI = 17;
  public static final int nou = 53;
  public static final int venter = 4;
  public static final int acaba = 47;
  public static final int PUNTICOMA = 20;
  public static final int per = 50;
  public static final int enter = 38;
  public static final int RCLAUDAT = 25;
  public static final int SUB = 8;
  public static final int decimal = 37;
  public static final int sino = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "vdecimal",
  "venter",
  "vlogic",
  "vcaracter",
  "ADD",
  "SUB",
  "MULT",
  "DIV",
  "MOD",
  "LPAREN",
  "RPAREN",
  "AUTOSUM",
  "AUTOSUB",
  "SUMAHI",
  "RESTAHI",
  "ASSIGN",
  "DOSPUNTS",
  "PUNTICOMA",
  "INTERROG",
  "LCORCH",
  "RCORCH",
  "LCLAUDAT",
  "RCLAUDAT",
  "PUNT",
  "COMA",
  "DIF",
  "IGIG",
  "MENORI",
  "MAJORI",
  "MENOR",
  "MAJOR",
  "OR",
  "AND",
  "NOT",
  "decimal",
  "enter",
  "logic",
  "caracter",
  "tupla",
  "si",
  "sino",
  "seleccio",
  "cas",
  "pdefecte",
  "acaba",
  "mentres",
  "fer",
  "per",
  "metode",
  "retorna",
  "nou",
  "constant",
  "entradaS",
  "sortidaS",
  "main",
  "borra",
  "afegeix"
  };
}

